---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-oidc-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: oidc-auth:8080
      allowed_request_headers:
      - "location"
      - "upgrade"
      - "x-forwarded-proto"
      - "x-forwarded-host"
      allowed_authorization_headers:
      - "set-cookie"
      - "www-authenticate"
      - "x-remote-user"
      - "x-remote-groups"
      - "x-tenant"
      - "x-trusted"
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  login_oidc_mapping
      prefix: /login/oidc
      rewrite: /login/oidc
      service: oidc-auth:8080
spec:
  type: ClusterIP
  selector:
    app: oidc-auth
  ports:
  - port: 8080
    name: http-oidc-auth
    targetPort: http-api
